# Generated by Django 4.0.2 on 2022-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='lorem ipsum dolor', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='lorem ipsum', max_length=100),
            preserve_default=False,
        ),
    ]
